{% set name = "whl2conda" %}
{% set version = "26.2.0" %}

package:
  name: whl2conda
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/whl2conda/whl2conda-{{ version }}.tar.gz
  sha256: d7b33bf501c1d8f80ce171dc26df4f7220cc5abce2a71bdc22e46e0d0de83587

build:
  entry_points:
    - whl2conda = whl2conda.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - conda-package-handling >=2.2
    - platformdirs >=3.10
    - pyyaml >=6.0
    - tomlkit >=0.12
    - wheel >=0.41

test:
  imports:
    - whl2conda.api
  commands:
    - pip check
    - whl2conda convert --help
  requires:
    - pip
    - requests
    - python {{ python_min }}

about:
  summary: build conda packages directly from pure python wheels
  home: https://github.com/zuzukin/whl2conda
  doc_url: https://zuzukin.github.io/whl2conda/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - analog-cbarber
