{% set name = "whl2conda" %}
{% set version = "23.8.10" %}

package:
  name: whl2conda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/whl2conda/whl2conda-{{ version }}.tar.gz
  sha256: 495850382a92b820defc77562d5509762fedd0d313baed2f38b40d762076f827

build:
  entry_points:
    - whl2conda = whl2conda.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - conda-package-handling >=2.2
    - platformdirs >=3.10
    - tomlkit >=0.12
    - wheel >=0.41

test:
  imports:
    - whl2conda.api
  commands:
    - pip check
    - whl2conda convert --help
  requires:
    - pip
    - requests

about:
  summary: build conda packages directly from pure python wheels
  home: https://github.com/zuzukin/whl2conda
  doc_url: https://zuzukin.github.io/whl2conda/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - analog-cbarber
